version: '3'

services:
  ai-content-generator-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp
    ports:
      - "8080:8080"
    depends_on:
      - gentle-service

  gentle-service:
    image: lowerquality/gentle:latest
    ports:
      - "8765:8765"