version: '3'

services:
  ai-content-generator-app:
    build: .
    environment:
      - logging.level.root=INFO
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - OPENAI_TOKEN=${OPENAI_TOKEN}
      - JWT_KEY=${JWT_KEY}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - gentle.aligner.url=http://gentle-service:8765
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SMARTPROXY_API_KEY=${SMARTPROXY_API_KEY}
    volumes:
      - ./download:/app/download
      - ./.log:/app/.log
      - ~/.config/gcloud:/root/.config/gcloud
      - ~/.bashrc:/root/.bashrc
    expose:
      - "8080"
    ports:
      - "8080:8080"

  gentle-service:
    image: lowerquality/gentle:latest
    ports:
      - "8765:8765"