version: '3'

services:
  ai-content-generator-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - elevenlabs.api.key=${{secrets.ELEVENLABS_API_KEY}}
      - openai.token=${{secrets.OPENAI_TOKEN}}
      - jwt.key=${{secrets.JWT_KEY}}
      - test.login.hashed.password=${{secrets.TEST_LOGIN_HASHED_PASSWORD}}
      - test.login.password=${{secrets.TEST_LOGIN_PASSWORD}}
      - supabase.apiKey=${{secrets.SUPABASE_API_KEY}}
      - spring.datasource.username=${{secrets.SPRING_DATASOURCE_USERNAME}}
      - spring.datasource.password=${{secrets.SPRING_DATASOURCE_PASSWORD}}
      - smartproxy.apiKey=${{secrets.SMARTPROXY_API_KEY}}
    volumes:
      - /tmp
    ports:
      - "8080:8080"
    depends_on:
      - gentle-service

  gentle-service:
    image: lowerquality/gentle:latest
    ports:
      - "8765:8765"