version: '3'

services:
  ai-content-generator-app:
    image: openjdk:17
    build: .
    environment:
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY} \
      - OPENAI_TOKEN=${OPENAI_TOKEN} \
      - JWT_KEY=${JWT_KEY} \
      - SUPABASE_API_KEY=${SUPABASE_API_KEY} \
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME} \
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD} \
      - SMARTPROXY_API_KEY=${SMARTPROXY_API_KEY} \
    volumes:
      - /tmp
    ports:
      - "8080:8080"
    depends_on:
      - gentle-service

  gentle-service:
    image: lowerquality/gentle:latest
    ports:
      - "8765:8765"